=== hichameyessou/XmlParser/message.dtd
<!ELEMENT  message (header, data+)>
<!ATTLIST message
	id ID #REQUIRED>

<!ELEMENT header (type, metadata*,format?)>

<!ELEMENT type EMPTY>
<!ATTLIST type
	id (normal | forward | reply) #REQUIRED
	reason CDATA "">

<!ELEMENT metadata EMPTY>
<!ATTLIST metadata 
	id ID #REQUIRED
	name CDATA #REQUIRED
	value CDATA "">
	
<!ELEMENT format EMPTY>
<!ATTLIST format
	type (plain|structured) "plain">	

<!ELEMENT data (#PCDATA|section)*>

<!ELEMENT section (#PCDATA|section|paragraph|figure|table|anchor|link)*>
<!ATTLIST section
	id ID #REQUIRED
	title CDATA #REQUIRED>
	
<!ELEMENT paragraph (#PCDATA)>

<!ELEMENT figure EMPTY>
<!ATTLIST figure
	id ID #REQUIRED
	caption CDATA #IMPLIED
	path CDATA "placeholder.jpg">

<!ELEMENT table (row+)>
<!ATTLIST table
	id ID #REQUIRED
	caption CDATA #REQUIRED>

<!ELEMENT row (cell+)>
<!ELEMENT cell (#PCDATA)>

<!ELEMENT anchor (#PCDATA)>
<!ATTLIST anchor
	id ID #REQUIRED>
	
<!ELEMENT link (#PCDATA)>
<!ATTLIST link
	target IDREF #REQUIRED
	title CDATA "">

=== hichameyessou/XmlParser/message2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE message SYSTEM "message.dtd" >
<message id="message2">
  <header>
    <type id="normal" reason=""/>
    <metadata id="thesender" name="sender" value="Mike"/>
    <metadata id="therecipient1" name="recipient" value="Luke"/>
    <format type="structured"/>
  </header>
  <data>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam consectetur, dolor nec gravida consectetur, quam ex vehicula purus, non tempus ante diam a sapien. Maecenas et lorem lectus. Quisque porttitor, tellus sit amet fringilla tempus, lectus nunc sollicitudin arcu, et auctor nibh diam a augue. Nam convallis nunc non risus sodales, ac blandit sem fringilla. Donec sagittis augue urna, ac euismod elit consectetur eu. Sed ac est dapibus, dictum libero sit amet, pellentesque turpis. Vivamus sit amet erat nunc. Nunc orci ipsum, placerat sit amet ultricies id, iaculis sit amet ante.
    <section id="secA" title="Sezione A">
      <paragraph>Mauris vitae pellentesque nibh. Ut feugiat sem sit amet ligula facilisis finibus. Etiam maximus odio id lacus rutrum consequat. Suspendisse sit amet purus nec augue lobortis facilisis non nec est. Nulla vitae nibh et ex gravida posuere. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam vehicula ultricies semper. Curabitur eleifend justo sed placerat posuere. Sed aliquet semper lacus. Ut gravida odio mollis, efficitur velit eu, tempus ipsum.</paragraph>
      <paragraph>Suspendisse mattis bibendum libero in ultrices. Duis feugiat diam in cursus sollicitudin. Ut bibendum hendrerit lacus, sed cursus tellus posuere non. Aliquam pellentesque nisl at eros vestibulum, accumsan gravida diam molestie. Praesent id justo ut nisi efficitur gravida. In elementum elit et scelerisque molestie. Quisque a tincidunt massa.</paragraph>
      <figure id="thefigure" path="folder/to/picture.png" />
    </section>
  </data>
</message>
